#!/usr/bin/env bash
# Build the book from the single Markdown source.
#   asterisk-guide[-LANG]            — CLEAN (no sponsor page); KDP paperback & local use
#   asterisk-guide-sponsored         — SPONSORED, English only, free PDF (the GitHub download)
# Usage:  book/build.sh [both|clean|sponsored]            (default: both)
#         BOOK_LANG=pt book/build.sh clean                # Portuguese edition (i18n/pt/chapters)
#         BOOK_LANG=es book/build.sh clean                # Spanish edition  (i18n/es/chapters)
# Translated chapters come from i18n/<lang>/chapters (generated by book/translate/translate.py);
# figures stay English (src/images) for every language.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/build"
SPONSORS="$ROOT/book/sponsors/sponsors.md"
INTERIOR="$ROOT/book/template/interior.tex"
mkdir -p "$OUT"

# Language selection: en (default) or a translated edition under i18n/<lang>/.
BOOK_LANG="${BOOK_LANG:-en}"
case "$BOOK_LANG" in
  en) SRC="$ROOT/src/chapters";     META="$ROOT/book/metadata.yaml";    SUF="" ;;
  pt) SRC="$ROOT/i18n/pt/chapters"; META="$ROOT/book/metadata-pt.yaml"; SUF="-pt" ;;
  es) SRC="$ROOT/i18n/es/chapters"; META="$ROOT/book/metadata-es.yaml"; SUF="-es" ;;
  *)  echo "Unknown BOOK_LANG '$BOOK_LANG' (use en|pt|es)" >&2; exit 1 ;;
esac
[ -d "$SRC" ] || { echo "No chapters at $SRC — run book/translate/translate.py --lang $BOOK_LANG first" >&2; exit 1; }

# Chapter order = numeric filename order. (portable: macOS bash 3.2 has no `mapfile`)
CHAPTERS=()
while IFS= read -r _f; do CHAPTERS+=("$_f"); done < <(ls "$SRC"/*.md | sort)

# Sponsored = the same chapters with the sponsor page inserted right after the front matter.
SPONSORED=()
for _f in "${CHAPTERS[@]}"; do
  SPONSORED+=("$_f")
  case "$_f" in *00-front-matter.md) SPONSORED+=("$SPONSORS") ;; esac
done

echo "Assembling ${#CHAPTERS[@]} chapters."

# commonmark_x is the GFM superset supporting {.unnumbered} headings and {width=} image attrs.
COMMON=( --from=commonmark_x
         --metadata-file="$META"
         --resource-path="$SRC:$ROOT:$ROOT/src/images:$ROOT/book/sponsors"
         --lua-filter="$ROOT/book/strip-notes.lua"
         --lua-filter="$ROOT/book/wrap-tables.lua"
         --toc --toc-depth=2 )

build_variant() {            # $1 = output name; remaining args = source files in order
  local name="$1"; shift
  local xf=()
  [ -n "${EXTRA_FILTER:-}" ] && xf=( --lua-filter="$EXTRA_FILTER" )   # per-chapter sponsor credits
  if [ "${PDF_ONLY:-0}" != "1" ]; then          # sponsored build is PDF-only (PDF_ONLY=1)
    echo "→ $name : EPUB"
    pandoc "${COMMON[@]}" "${xf[@]}" -o "$OUT/$name.epub" "$@"
  fi
  echo "→ $name : PDF (xelatex)"
  pandoc "${COMMON[@]}" "${xf[@]}" --pdf-engine=xelatex --include-in-header="$INTERIOR" -o "$OUT/$name.pdf" "$@"
}

want="${1:-both}"

# Clean variant — every language (PDF + EPUB + LaTeX).
if [ "$want" != "sponsored" ]; then
  build_variant "asterisk-guide$SUF" "${CHAPTERS[@]}"
  echo "→ asterisk-guide$SUF : LaTeX"
  pandoc "${COMMON[@]}" --standalone --include-in-header="$INTERIOR" -o "$OUT/asterisk-guide$SUF.tex" "${CHAPTERS[@]}"
fi

# Sponsored variant — English only (the sponsor pages are in English). Free PDF download.
if [ "$want" != "clean" ] && [ "$BOOK_LANG" = "en" ]; then
  EXTRA_FILTER="$ROOT/book/inject-sponsors.lua" PDF_ONLY=1 \
    build_variant "asterisk-guide-sponsored" "${SPONSORED[@]}"
fi

echo "Done. Artifacts in $OUT:"
ls -la "$OUT"
